name: fms
description: 'A new Flutter project.'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_screenutil: 5.9.3
  flutter_svg: ^2.2.2
  # 위치구하기
  geolocator: 14.0.2
  baseflow_plugin_template: 2.2.0

  # 도트 보더
  dotted_border: 3.1.0

  # image picker
  image_picker: 1.2.0

  # provider
  provider: 6.1.5+1

  # hive
  hive_flutter: 1.1.0
  hive: 2.2.3

  # path_provider
  path_provider: ^2.1.5

  #intl
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Hive
  build_runner: ^2.4.13
  hive_generator: 2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900

  assets:
    - assets/icon/
